# build-data.ps1 - take a snapshot and write the dashboard's data file.
#
# Writes two things next to the dashboard, both generated and both gitignored:
#   data.js       the current snapshot plus the kept history, as one assignment
#   history.jsonl one compact line per snapshot, append-only
#
# `data.js` is an assignment rather than a .json file on purpose: a browser
# opening index.html from a file:// path cannot fetch() a sibling file, but it
# can always load a sibling <script>. So the dashboard needs no server, no CORS
# exception and no build tooling.
#
# History is kept here because HarborMaster does not yet retain readings
# (CHARTER Sec. 5.4). Every run appends one point, so the time-series panel fills in
# as the tool is used rather than waiting for the telemetry milestone.

[CmdletBinding()]
param(
    [string]$Exe,
    [int]$KeepDays = 90
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $PSScriptRoot          # ...\dashboard
$repo = Split-Path -Parent $here                  # repo root

if (-not $Exe) {
    foreach ($c in @("$repo\target\release\harbormaster.exe", "$repo\target\debug\harbormaster.exe")) {
        if (Test-Path $c) { $Exe = $c; break }
    }
}
if (-not $Exe -or -not (Test-Path $Exe)) {
    throw "No built binary found. Run 'cargo build' first, or pass -Exe <path>."
}

Write-Host "snapshot via $Exe ..."
$raw = & $Exe --probe --json 2>$null
if ($LASTEXITCODE -ne 0 -or -not $raw) { throw "probe failed (exit $LASTEXITCODE)" }

$snap = $raw | ConvertFrom-Json
if (-not $snap.schema) { throw "unexpected probe output: no schema field" }

# ── append one history point ────────────────────────────────────────────────
# Deliberately narrow: a full snapshot per run would grow without bound and most
# of it does not change. Latency is the series worth keeping per snapshot; the
# dense per-minute telemetry gets its own store when Sec. 5.4 lands.
$latency = @{}
foreach ($r in $snap.rows) {
    if ($r.http) { $latency[$r.project.slug] = $r.http.latency_ms }
}
# Assigned before the hashtable, not inline: `if` as an expression is PowerShell
# 7 syntax and this script has to parse under Windows PowerShell 5.1 too, where
# it is a parse error - and a parse error reports at the wrong line.
$memPct = $null
if ($snap.host) { $memPct = $snap.host.mem_pct }

$point = [ordered]@{
    t       = $snap.generated
    healthy = $snap.totals.healthy
    total   = $snap.totals.projects
    gaps    = $snap.gaps.Count
    mem_pct = $memPct
    latency = $latency
}

$histPath = Join-Path $here 'history.jsonl'
($point | ConvertTo-Json -Compress -Depth 6) | Add-Content -Path $histPath -Encoding utf8

# Read back, dropping anything older than the retention window and any line that
# does not parse - a truncated write must not take the dashboard down with it.
$cutoff = (Get-Date).ToUniversalTime().AddDays(-$KeepDays)
$history = @()
foreach ($line in Get-Content $histPath -Encoding utf8) {
    if (-not $line.Trim()) { continue }
    try { $o = $line | ConvertFrom-Json } catch { continue }
    if ([datetime]::Parse($o.t).ToUniversalTime() -ge $cutoff) { $history += $o }
}

# ── write data.js ───────────────────────────────────────────────────────────
$payload = [ordered]@{ snapshot = $snap; history = $history }
$json = $payload | ConvertTo-Json -Depth 12 -Compress
$body = "/* generated by scripts/build-data.ps1 - do not edit */" + [Environment]::NewLine +
        "window.__HM__ = " + $json + ";" + [Environment]::NewLine

# UTF-8 without BOM: a BOM ahead of the assignment is a syntax error in a script tag.
[System.IO.File]::WriteAllText((Join-Path $here 'data.js'), $body, (New-Object System.Text.UTF8Encoding $false))

$msg = "data.js written - {0} cargo, {1} gap(s), {2} snapshot(s) kept"
Write-Host ($msg -f $snap.totals.projects, $snap.gaps.Count, $history.Count)
Write-Host ("open: " + (Join-Path $here 'index.html'))
